### ISSUE TITLE
Matrix selector does not open with Android Studio Ladybug

### ISSUE THREAD

**Issue by Dukoff92** [Nilzor/build-variant-matrix#15]
Thank you for creating the plugin, it is reallyuseful.
However, upon updating to the new Ladybug version of Android studio it stopped working.
Whenever I try to open the matrix selector from the **Build** dropdown menu nothing happens.

**Comment by Nilzor** [comment]
Thanks for the notifiying me. I will look into this shortly

**Comment by Nilzor** [comment]
Fix is now released under files [here](https://github.com/Nilzor/build-variant-matrix/releases/tag/1.3.0), and is pending review for official release through the Jetbrains reposiotory. That channel will normally take a couple of days to pass.
