### ISSUE TITLE
Selected variant resets every time Android Studio gets updated

### ISSUE THREAD

**Issue by mustafacakirogludev** [Nilzor/build-variant-matrix#17]
Greetings, love the plugin but I noticed every time I update AS(which is a lot because I use beta/canary versions) the selected variants gets reset. I usually don't notice until I ran the app and its the wrong configuration and since I work on a big project it can waste a lot of time. I am not sure if this is something that can be improved, is it possible to make it so the chosen variant persists through AS updates? Thanks!

**Comment by Nilzor** [comment]
I really don't think that's a problem with the plugin. There is no persistance done by the plugin. No storage. It's Android Studio's responsibility to remember

**Comment by Nilzor** [comment]
he

**Comment by Nilzor** [comment]
closing . Post back if you have any new information that may change my opinion
