### ISSUE TITLE
0.6 doesn't work with Android Studio 4.2.1

### ISSUE THREAD

**Issue by dmitry-ryadnenko-izettle** [Nilzor/build-variant-matrix#2]
After update to 0.6 I still can't switch build variants.

**Comment by Nilzor** [comment]
Hi, Are you still in Android Studio 4.2.1? Try updating either to 4.2.2 (plugin 0.6) or to Arctic Fox (aka Anroid Studio 4.3) with v0.7.0 of the plugin.
