### ISSUE TITLE
doesn't work on that latest AS build AI-203.7717.56

### ISSUE THREAD

**Issue by peterstev-fm** [Nilzor/build-variant-matrix#3]
Plugin 'Build Variant Matrix Selector' (version '0.6.0') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is AI-203.7717.56

**Comment by Nilzor** [comment]
Thanks for notifying me. I'll be fixing this ASAP and get back to you

**Comment by Nilzor** [comment]
Fix implemented, built and uploaded to Jetbrains for approval

**Comment by Nilzor** [comment]
Approved and published in the stable plugin channel.

Closing the issue, but do let me know if you still have problems
