### ISSUE TITLE
Doesn't work on AS Chipmunk

### ISSUE THREAD

**Issue by rishabhkohli** [Nilzor/build-variant-matrix#5]
As the title states, this plugin doesn't work with AS Chipmunk, using the latest (RC1) build.

**Comment by Nilzor** [comment]
Chipmunk RC2 build supported from v0.9,93, submittet to beta channel today. Will update issue once in production. Production version will be 1.0.0

https://github.com/Nilzor/build-variant-matrix/pull/6

**Comment by Nilzor** [comment]
Beta release 0.9.93 with fix available for download at https://plugins.jetbrains.com/plugin/15632-build-variant-matrix-selector/versions/beta

Release in production channel published but awaiting approval. Will post and close issue when production channel release is approved

**Comment by rishabhkohli** [comment]
Works now. 
Thanks.
